name: ci-security

on:
  pull_request:
  push:
    branches: [ main, rgpd ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important pour que git ait tout l'historique

      - name: Run gitleaks
        uses: zricethezav/gitleaks-action@v2.3.7
        with:
          args: detect --source . --redact --report-format sarif --report-path results.sarif
